[2.1] sortStrings
js-tasks-ru/js-20220513_andrey772 pull request #2
Opened 2022-05-19 15:59 UTC by asromanychev

2022-05-19 16:01 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-20 03:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-20 03:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-20 12:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let collator = new Intl.Collator('ru', {sensitivity: 'case', caseFirst: 'upper'});
проверьте, может `collator` это `const`?

2022-05-20 12:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newarr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-05-20 12:30 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const subset = Object.fromEntries(fields.filter(key => key in obj).map(key => [key, obj[key]]));
good 👍

2022-05-20 12:30 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
👍 good

2022-05-20 12:30 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-05-21 02:45 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-21 03:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-21 03:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-22 04:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-22 10:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-23 03:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-23 03:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-24 07:14 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return path.split(".").reduce((prev, curr) => prev && prev[curr], obj);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-05-24 07:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
мы не обращаемся к `undefined` напрямую.
достаточно просто `return`

2022-05-24 07:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2022-05-24 07:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-05-24 07:18 UTC, dosandk approved these changes
good 👍
посмотрите комент к `createGetter`, решение принято, но следует поправить код

2022-05-24 07:20 UTC, merged